server:
  port: 8000

spring:
  application:
    name: EUREKA-GATEWAY
  cloud:
    gateway:
      httpclient:
        connect-timeout: 50000
        response-timeout: 50000

        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
        globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins:
                - 'http://localhost:3000'
              allow-credentials: true
              allowedHeaders: '*'
              allowedMethods:
                - PUT
                - GET
                - POST
                - DELETE
                - PATCH
                - OPTIONS
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: CLIENT-SERVICE
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/api/v1/client/**
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payment/**
        - id: RESERVATION-SERVICE
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/api/v1/reservation/**
        - id: ADMIN-SERVICE
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/api/v1/admin/**
        - id : REVIEW-BOOKMARK-SERVICE
          uri: lb://REVIEW-BOOKMARK-SERVICE
          predicates:
            - Path=/api/v1/review-bookmark/**
        - id : SETTLE-SERVICE
          uri : lb://SETTLE-SERVICE
          predicates:
            - Path=/api/v1/settle/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

